#!/bin/sh

set -e
WORKDIR="$(pwd)"
cd "$(dirname "$0")"
UMLDIR="$(pwd)"
echo "$@" > "${UMLDIR}/.command"
export -p > "${UMLDIR}/.envp"
rm -f "${UMLDIR}/.exit_code"

QUIET=${QUIET:-0}
DOCKER_PORT=${DOCKER_PORT:-2375}
HOSTIP=$(ip addr | grep 'scope global' | head -n1 | awk '{print $2}' | cut -f1  -d'/')

# Create a silent slirp-wrapper script
echo '#!/bin/sh -e' > "${UMLDIR}/slirp-wrapper"
chmod +x "${UMLDIR}/slirp-wrapper"
if [ "${QUIET}" -eq 1 ]; then
    echo "exec /usr/bin/slirp-fullbolt -S 'redir ${DOCKER_PORT} 2375' 'host addr ${HOSTIP}' '\$@' 2>/dev/null" >> "${UMLDIR}/slirp-wrapper"
else
    echo "exec /usr/bin/slirp-fullbolt -S 'redir ${DOCKER_PORT} 2375' 'host addr ${HOSTIP}' '\$@'" >> "${UMLDIR}/slirp-wrapper"
fi

(
    test "${QUIET}" -eq 0 && set -x
    sudo "${UMLDIR}/linux" \
	quiet \
	mem=2G \
	rootfstype=hostfs rw \
	eth0=slirp,,"${UMLDIR}/slirp-wrapper" \
	"init=${UMLDIR}/linux-init" \
	"WORKDIR=${WORKDIR}" \
	"UMLDIR=${UMLDIR}" \
	"QUIET=${QUIET}" \
	"DOCKER_STORAGE_DRIVER=${DOCKER_STORAGE_DRIVER:-devicemapper}"
)

exit_code=$(cat "${UMLDIR}/.exit_code")
eval exit ${exit_code}
